export let tokens = [
  {
    index: 0,
    name: 'axs',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=axie-infinity&vs_currencies=usd',
    path: 'axie-infinity',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 1,
    name: 'slp',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=smooth-love-potion&vs_currencies=usd',
    path: 'smooth-love-potion',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 2,
    name: 'bcoin',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=bomber-coin&vs_currencies=usd',
    path: 'bomber-coin',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 3,
    name: 'atlas',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=star-atlas&vs_currencies=usd',
    path: 'star-atlas',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 4,
    name: 'thg',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=thetan-arena&vs_currencies=usd',
    path: 'thetan-arena',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 5,
    name: 'thc',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=thetan-coin&vs_currencies=usd',
    path: 'thetan-coin',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 6,
    name: 'ccar',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=cryptocars&vs_currencies=usd',
    path: 'cryptocars',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 7,
    name: 'cpan',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=cryptoplanes&vs_currencies=usd',
    path: 'cryptoplanes',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 8,
    name: 'cgar',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=cryptoguards&vs_currencies=usd',
    path: 'cryptoguards',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 9,
    name: 'orkl',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=orakler&vs_currencies=usd',
    path: 'orakler',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 10,
    name: 'cwolf',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=cryptowolf&vs_currencies=usd',
    path: 'cryptowolf',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 11,
    name: 'fvp',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=fishervspirate&vs_currencies=usd',
    path: 'fishervspirate',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 12,
    name: 'gem',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=age-of-knights&vs_currencies=usd',
    path: 'age-of-knights',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  },
  {
    index: 13,
    name: 'rps',
    api: 'https://api.coingecko.com/api/v3/simple/price?ids=rps-league&vs_currencies=usd',
    path: 'rps-league',
    act: false,
    price: 0,
    input: null,
    balance: 'Enter your tokens',
  }
];
